

export const Icons = [
'/assets/icons/colour-cirle-set/office/paper.png',
'/assets/icons/colour-cirle-set/office/envelope.png',
'/assets/icons/colour-cirle-set/office/mail.png',
'/assets/icons/colour-cirle-set/office/talk.png',
'/assets/icons/colour-cirle-set/office/calender.png',
'/assets/icons/colour-cirle-set/office/information.png',
'/assets/icons/colour-cirle-set/office/folder document.png',
'/assets/icons/colour-cirle-set/office/folder.png',
'/assets/icons/colour-cirle-set/office/man.png',
'/assets/icons/colour-cirle-set/office/paper plane.png',
'/assets/icons/colour-cirle-set/office/location.png',
'/assets/icons/colour-cirle-set/office/phone.png',
'/assets/icons/colour-cirle-set/office/clock.png',
'/assets/icons/colour-cirle-set/office/woman.png',
'/assets/icons/colour-cirle-set/office/education.png',
'/assets/icons/colour-cirle-set/office/paper clip.png',
'/assets/icons/colour-cirle-set/web/check.png',
'/assets/icons/colour-cirle-set/web/stop.png',
'/assets/icons/colour-cirle-set/web/tick.png',
'/assets/icons/colour-cirle-set/web/link.png',
'/assets/icons/colour-cirle-set/web/curser.png',
'/assets/icons/colour-cirle-set/web/power.png',
'/assets/icons/colour-cirle-set/web/zoom in.png',
'/assets/icons/colour-cirle-set/web/zoom out.png',
'/assets/icons/colour-cirle-set/web/download from cloud.png',
'/assets/icons/colour-cirle-set/web/upload.png',
'/assets/icons/colour-cirle-set/web/cloud.png',
'/assets/icons/colour-cirle-set/web/cross.png',
'/assets/icons/colour-cirle-set/web/refresh 2.png',
'/assets/icons/colour-cirle-set/web/upload to cloud.png',
'/assets/icons/colour-cirle-set/web/star.png',
'/assets/icons/colour-cirle-set/web/refresh.png',
'/assets/icons/colour-cirle-set/business/news.png',
'/assets/icons/colour-cirle-set/business/mail.png',
'/assets/icons/colour-cirle-set/business/lock.png',
'/assets/icons/colour-cirle-set/business/screw driver.png',
'/assets/icons/colour-cirle-set/business/strategy.png',
'/assets/icons/colour-cirle-set/business/speed.png',
'/assets/icons/colour-cirle-set/business/tag.png',
'/assets/icons/colour-cirle-set/business/presentation.png',
'/assets/icons/colour-cirle-set/business/chart.png',
'/assets/icons/colour-cirle-set/business/cog.png',
'/assets/icons/colour-cirle-set/business/tools.png',
'/assets/icons/colour-cirle-set/business/guarentee.png',
'/assets/icons/colour-cirle-set/business/brief case.png',
'/assets/icons/colour-cirle-set/business/unlock.png',
'/assets/icons/colour-cirle-set/business/award.png',
'/assets/icons/colour-cirle-set/business/spanner.png',
'/assets/icons/colour-cirle-set/marketing/email.png',
'/assets/icons/colour-cirle-set/marketing/arrow increase.png',
'/assets/icons/colour-cirle-set/marketing/direction.png',
'/assets/icons/colour-cirle-set/marketing/book.png',
'/assets/icons/colour-cirle-set/marketing/broswer star.png',
'/assets/icons/colour-cirle-set/marketing/bill board.png',
'/assets/icons/colour-cirle-set/marketing/light bulb.png',
'/assets/icons/colour-cirle-set/marketing/target.png',
'/assets/icons/colour-cirle-set/marketing/promote.png',
'/assets/icons/colour-cirle-set/marketing/search.png',
'/assets/icons/colour-cirle-set/marketing/heart.png',
'/assets/icons/colour-cirle-set/marketing/pulse.png',
'/assets/icons/colour-cirle-set/marketing/shopping basket.png',
'/assets/icons/colour-cirle-set/marketing/mountain.png',
'/assets/icons/colour-cirle-set/marketing/shopping bag.png',
'/assets/icons/colour-cirle-set/marketing/globe network.png',
'/assets/icons/colour-cirle-set/marketing/eye.png',
'/assets/icons/colour-cirle-set/marketing/pencil.png',
'/assets/icons/colour-cirle-set/marketing/idea.png',
'/assets/icons/colour-cirle-set/marketing/compass.png',
'/assets/icons/colour-cirle-set/marketing/display board.png',
'/assets/icons/colour-cirle-set/marketing/browser.png',
'/assets/icons/colour-cirle-set/marketing/converstion.png',
'/assets/icons/colour-cirle-set/marketing/camera.png',
'/assets/icons/colour-cirle-set/analytics/code.png',
'/assets/icons/colour-cirle-set/analytics/line graph.png',
'/assets/icons/colour-cirle-set/analytics/arrow graph.png',
'/assets/icons/colour-cirle-set/analytics/bar chart.png',
'/assets/icons/colour-cirle-set/analytics/chart browser.png',
'/assets/icons/colour-cirle-set/analytics/ie chart 2.png',
'/assets/icons/colour-cirle-set/analytics/pie chart.png',
'/assets/icons/colour-cirle-set/analytics/pulse.png',
'/assets/icons/colour-cirle-set/analytics/structure.png',
'/assets/icons/colour-cirle-set/analytics/visual date.png',
'/assets/icons/colour-cirle-set/analytics/filter.png',
'/assets/icons/colour-cirle-set/analytics/bar graph.png',
'/assets/icons/colour-cirle-set/analytics/analytics.png',
'/assets/icons/colour-cirle-set/analytics/adjust.png',
'/assets/icons/colour-cirle-set/analytics/experiment.png',
'/assets/icons/colour-cirle-set/analytics/network.png',
'/assets/icons/icon-192x192.png',
'/assets/icons/icon-384x384.png',
'/assets/icons/icon-72x72.png',
'/assets/icons/icon-96x96.png',
'/assets/icons/icon-152x152.png',
'/assets/icons/dark-set/office/paper.png',
'/assets/icons/dark-set/office/folder paper.png',
'/assets/icons/dark-set/office/envelope.png',
'/assets/icons/dark-set/office/mail.png',
'/assets/icons/dark-set/office/calender.png',
'/assets/icons/dark-set/office/information.png',
'/assets/icons/dark-set/office/folder.png',
'/assets/icons/dark-set/office/man.png',
'/assets/icons/dark-set/office/pjone.png',
'/assets/icons/dark-set/office/quote.png',
'/assets/icons/dark-set/office/paper plane.png',
'/assets/icons/dark-set/office/clock.png',
'/assets/icons/dark-set/office/woman.png',
'/assets/icons/dark-set/office/education.png',
'/assets/icons/dark-set/office/location pin.png',
'/assets/icons/dark-set/office/paper clip.png',
'/assets/icons/dark-set/web/stop.png',
'/assets/icons/dark-set/web/tick.png',
'/assets/icons/dark-set/web/on off.png',
'/assets/icons/dark-set/web/zoom in.png',
'/assets/icons/dark-set/web/zoom out.png',
'/assets/icons/dark-set/web/tick check.png',
'/assets/icons/dark-set/web/download from cloud.png',
'/assets/icons/dark-set/web/upload.png',
'/assets/icons/dark-set/web/cloud.png',
'/assets/icons/dark-set/web/cross.png',
'/assets/icons/dark-set/web/refresh 2.png',
'/assets/icons/dark-set/web/upload to cloud.png',
'/assets/icons/dark-set/web/links.png',
'/assets/icons/dark-set/web/star.png',
'/assets/icons/dark-set/web/arrow curser.png',
'/assets/icons/dark-set/web/refresh.png',
'/assets/icons/dark-set/business/news.png',
'/assets/icons/dark-set/business/mail.png',
'/assets/icons/dark-set/business/lock.png',
'/assets/icons/dark-set/business/screw driver.png',
'/assets/icons/dark-set/business/strategy.png',
'/assets/icons/dark-set/business/speed.png',
'/assets/icons/dark-set/business/tag.png',
'/assets/icons/dark-set/business/presentation.png',
'/assets/icons/dark-set/business/chart.png',
'/assets/icons/dark-set/business/cog.png',
'/assets/icons/dark-set/business/tools.png',
'/assets/icons/dark-set/business/guarentee.png',
'/assets/icons/dark-set/business/brief case.png',
'/assets/icons/dark-set/business/unlock.png',
'/assets/icons/dark-set/business/award.png',
'/assets/icons/dark-set/business/spanner.png',
'/assets/icons/dark-set/marketing/email.png',
'/assets/icons/dark-set/marketing/arrow increase.png',
'/assets/icons/dark-set/marketing/book.png',
'/assets/icons/dark-set/marketing/sign post.png',
'/assets/icons/dark-set/marketing/browser star.png',
'/assets/icons/dark-set/marketing/bill board.png',
'/assets/icons/dark-set/marketing/light bulb.png',
'/assets/icons/dark-set/marketing/target.png',
'/assets/icons/dark-set/marketing/search.png',
'/assets/icons/dark-set/marketing/heart.png',
'/assets/icons/dark-set/marketing/pulse.png',
'/assets/icons/dark-set/marketing/shopping basket.png',
'/assets/icons/dark-set/marketing/mountains.png',
'/assets/icons/dark-set/marketing/globe.png',
'/assets/icons/dark-set/marketing/shopping bag.png',
'/assets/icons/dark-set/marketing/display.png',
'/assets/icons/dark-set/marketing/marketing.png',
'/assets/icons/dark-set/marketing/conversation.png',
'/assets/icons/dark-set/marketing/eye.png',
'/assets/icons/dark-set/marketing/pencil.png',
'/assets/icons/dark-set/marketing/idea.png',
'/assets/icons/dark-set/marketing/compass.png',
'/assets/icons/dark-set/marketing/browser.png',
'/assets/icons/dark-set/marketing/camera.png',
'/assets/icons/dark-set/analytics/pie chart 2.png',
'/assets/icons/dark-set/analytics/code.png',
'/assets/icons/dark-set/analytics/line graph.png',
'/assets/icons/dark-set/analytics/data graph.png',
'/assets/icons/dark-set/analytics/arrow graph.png',
'/assets/icons/dark-set/analytics/bar chart.png',
'/assets/icons/dark-set/analytics/pie chart.png',
'/assets/icons/dark-set/analytics/pulse.png',
'/assets/icons/dark-set/analytics/visual data.png',
'/assets/icons/dark-set/analytics/structure.png',
'/assets/icons/dark-set/analytics/filter.png',
'/assets/icons/dark-set/analytics/browser graph.png',
'/assets/icons/dark-set/analytics/analytics.png',
'/assets/icons/dark-set/analytics/adjust.png',
'/assets/icons/dark-set/analytics/experiment.png',
'/assets/icons/dark-set/analytics/network.png',
'/assets/icons/icon-512x512.png',
'/assets/icons/light-set/office/paper.png',
'/assets/icons/light-set/office/folder paper.png',
'/assets/icons/light-set/office/envelope.png',
'/assets/icons/light-set/office/mail.png',
'/assets/icons/light-set/office/talk.png',
'/assets/icons/light-set/office/calender.png',
'/assets/icons/light-set/office/information.png',
'/assets/icons/light-set/office/folder.png',
'/assets/icons/light-set/office/man.png',
'/assets/icons/light-set/office/paper plane.png',
'/assets/icons/light-set/office/location.png',
'/assets/icons/light-set/office/phone.png',
'/assets/icons/light-set/office/clock.png',
'/assets/icons/light-set/office/woman.png',
'/assets/icons/light-set/office/education.png',
'/assets/icons/light-set/office/paper clip.png',
'/assets/icons/light-set/web/check.png',
'/assets/icons/light-set/web/stop.png',
'/assets/icons/light-set/web/tick.png',
'/assets/icons/light-set/web/link.png',
'/assets/icons/light-set/web/on off.png',
'/assets/icons/light-set/web/zoom in.png',
'/assets/icons/light-set/web/arrow.png',
'/assets/icons/light-set/web/zoom out.png',
'/assets/icons/light-set/web/download from cloud.png',
'/assets/icons/light-set/web/upload.png',
'/assets/icons/light-set/web/cloud.png',
'/assets/icons/light-set/web/cross.png',
'/assets/icons/light-set/web/refresh 2.png',
'/assets/icons/light-set/web/upload to cloud.png',
'/assets/icons/light-set/web/favorite.png',
'/assets/icons/light-set/web/refresh.png',
'/assets/icons/light-set/business/news.png',
'/assets/icons/light-set/business/email.png',
'/assets/icons/light-set/business/screw driver.png',
'/assets/icons/light-set/business/strategy.png',
'/assets/icons/light-set/business/speed.png',
'/assets/icons/light-set/business/presentation.png',
'/assets/icons/light-set/business/chart.png',
'/assets/icons/light-set/business/cog.png',
'/assets/icons/light-set/business/tools.png',
'/assets/icons/light-set/business/price tag.png',
'/assets/icons/light-set/business/locked.png',
'/assets/icons/light-set/business/guarentee.png',
'/assets/icons/light-set/business/brief case.png',
'/assets/icons/light-set/business/unlocked.png',
'/assets/icons/light-set/business/award.png',
'/assets/icons/light-set/business/spanner.png',
'/assets/icons/light-set/marketing/email.png',
'/assets/icons/light-set/marketing/arrow up.png',
'/assets/icons/light-set/marketing/book.png',
'/assets/icons/light-set/marketing/sign post.png',
'/assets/icons/light-set/marketing/browser star.png',
'/assets/icons/light-set/marketing/speaking.png',
'/assets/icons/light-set/marketing/bill board.png',
'/assets/icons/light-set/marketing/light bulb.png',
'/assets/icons/light-set/marketing/target.png',
'/assets/icons/light-set/marketing/megaphone.png',
'/assets/icons/light-set/marketing/search.png',
'/assets/icons/light-set/marketing/heart.png',
'/assets/icons/light-set/marketing/basket.png',
'/assets/icons/light-set/marketing/pulse.png',
'/assets/icons/light-set/marketing/mountain.png',
'/assets/icons/light-set/marketing/globe.png',
'/assets/icons/light-set/marketing/shopping bag.png',
'/assets/icons/light-set/marketing/display.png',
'/assets/icons/light-set/marketing/eye.png',
'/assets/icons/light-set/marketing/pencil.png',
'/assets/icons/light-set/marketing/idea.png',
'/assets/icons/light-set/marketing/compass.png',
'/assets/icons/light-set/marketing/browser.png',
'/assets/icons/light-set/marketing/camera.png',
'/assets/icons/light-set/analytics/pie chart 2.png',
'/assets/icons/light-set/analytics/code.png',
'/assets/icons/light-set/analytics/line graph.png',
'/assets/icons/light-set/analytics/data graph.png',
'/assets/icons/light-set/analytics/arrow graph.png',
'/assets/icons/light-set/analytics/bar chart.png',
'/assets/icons/light-set/analytics/eye pie chart.png',
'/assets/icons/light-set/analytics/pie chart.png',
'/assets/icons/light-set/analytics/pulse.png',
'/assets/icons/light-set/analytics/structure.png',
'/assets/icons/light-set/analytics/filter.png',
'/assets/icons/light-set/analytics/analytics.png',
'/assets/icons/light-set/analytics/graph browser.png',
'/assets/icons/light-set/analytics/adjust.png',
'/assets/icons/light-set/analytics/experiment.png',
'/assets/icons/light-set/analytics/network.png',
'/assets/icons/icon-144x144.png',
'/assets/icons/colour-accent-set/office/document.png',
'/assets/icons/colour-accent-set/office/envelope.png',
'/assets/icons/colour-accent-set/office/mail.png',
'/assets/icons/colour-accent-set/office/calender.png',
'/assets/icons/colour-accent-set/office/information.png',
'/assets/icons/colour-accent-set/office/folder.png',
'/assets/icons/colour-accent-set/office/folder documnet.png',
'/assets/icons/colour-accent-set/office/man.png',
'/assets/icons/colour-accent-set/office/paper plane.png',
'/assets/icons/colour-accent-set/office/location.png',
'/assets/icons/colour-accent-set/office/phone.png',
'/assets/icons/colour-accent-set/office/clock.png',
'/assets/icons/colour-accent-set/office/woman.png',
'/assets/icons/colour-accent-set/office/education.png',
'/assets/icons/colour-accent-set/office/speech.png',
'/assets/icons/colour-accent-set/office/paper clip.png',
'/assets/icons/colour-accent-set/web/stop.png',
'/assets/icons/colour-accent-set/web/tick.png',
'/assets/icons/colour-accent-set/web/link.png',
'/assets/icons/colour-accent-set/web/on off.png',
'/assets/icons/colour-accent-set/web/curser.png',
'/assets/icons/colour-accent-set/web/zoom in.png',
'/assets/icons/colour-accent-set/web/zoom out.png',
'/assets/icons/colour-accent-set/web/tick check.png',
'/assets/icons/colour-accent-set/web/download from cloud.png',
'/assets/icons/colour-accent-set/web/upload.png',
'/assets/icons/colour-accent-set/web/cloud.png',
'/assets/icons/colour-accent-set/web/cross.png',
'/assets/icons/colour-accent-set/web/refresh 2.png',
'/assets/icons/colour-accent-set/web/upload to cloud.png',
'/assets/icons/colour-accent-set/web/star.png',
'/assets/icons/colour-accent-set/web/refresh.png',
'/assets/icons/colour-accent-set/business/news.png',
'/assets/icons/colour-accent-set/business/mail.png',
'/assets/icons/colour-accent-set/business/screw driver.png',
'/assets/icons/colour-accent-set/business/strategy.png',
'/assets/icons/colour-accent-set/business/speed.png',
'/assets/icons/colour-accent-set/business/tag.png',
'/assets/icons/colour-accent-set/business/presentation.png',
'/assets/icons/colour-accent-set/business/chart.png',
'/assets/icons/colour-accent-set/business/cog.png',
'/assets/icons/colour-accent-set/business/tools.png',
'/assets/icons/colour-accent-set/business/locked.png',
'/assets/icons/colour-accent-set/business/guarentee.png',
'/assets/icons/colour-accent-set/business/brief case.png',
'/assets/icons/colour-accent-set/business/unlocked.png',
'/assets/icons/colour-accent-set/business/award.png',
'/assets/icons/colour-accent-set/business/spanner.png',
'/assets/icons/colour-accent-set/marketing/email.png',
'/assets/icons/colour-accent-set/marketing/arrow increase.png',
'/assets/icons/colour-accent-set/marketing/book.png',
'/assets/icons/colour-accent-set/marketing/sign post.png',
'/assets/icons/colour-accent-set/marketing/browser star.png',
'/assets/icons/colour-accent-set/marketing/bill board.png',
'/assets/icons/colour-accent-set/marketing/light bulb.png',
'/assets/icons/colour-accent-set/marketing/target.png',
'/assets/icons/colour-accent-set/marketing/promote.png',
'/assets/icons/colour-accent-set/marketing/mauntain.png',
'/assets/icons/colour-accent-set/marketing/search.png',
'/assets/icons/colour-accent-set/marketing/heart.png',
'/assets/icons/colour-accent-set/marketing/pulse.png',
'/assets/icons/colour-accent-set/marketing/shopping basket.png',
'/assets/icons/colour-accent-set/marketing/shopping bag.png',
'/assets/icons/colour-accent-set/marketing/globe network.png',
'/assets/icons/colour-accent-set/marketing/eye.png',
'/assets/icons/colour-accent-set/marketing/pencil.png',
'/assets/icons/colour-accent-set/marketing/idea.png',
'/assets/icons/colour-accent-set/marketing/compass.png',
'/assets/icons/colour-accent-set/marketing/display board.png',
'/assets/icons/colour-accent-set/marketing/browser.png',
'/assets/icons/colour-accent-set/marketing/converstion.png',
'/assets/icons/colour-accent-set/marketing/camera.png',
'/assets/icons/colour-accent-set/analytics/pie chart 2.png',
'/assets/icons/colour-accent-set/analytics/colour accent set 128x128-37.png',
'/assets/icons/colour-accent-set/analytics/code.png',
'/assets/icons/colour-accent-set/analytics/bar chart.png',
'/assets/icons/colour-accent-set/analytics/browser chart.png',
'/assets/icons/colour-accent-set/analytics/pie chart.png',
'/assets/icons/colour-accent-set/analytics/visual data.png',
'/assets/icons/colour-accent-set/analytics/structure.png',
'/assets/icons/colour-accent-set/analytics/filter.png',
'/assets/icons/colour-accent-set/analytics/analytics.png',
'/assets/icons/colour-accent-set/analytics/adjust.png',
'/assets/icons/colour-accent-set/analytics/line chart.png',
'/assets/icons/colour-accent-set/analytics/experiment.png',
'/assets/icons/colour-accent-set/analytics/data chart.png',
'/assets/icons/colour-accent-set/analytics/network.png',
'/assets/icons/colour-accent-set/analytics/arrow chart.png',
'/assets/icons/icon-128x128.png',
'/assets/icons/facebook.png',
'/assets/icons/xing.png',
'/assets/icons/instagram.png',
'/assets/icons/tumblr.png',
'/assets/icons/linkedin.png',
'/assets/icons/twitter.png',
'/assets/icons/github.png',
'/assets/icons/instagram.png',
'/assets/icons/web.png',
'/assets/icons/snapchat.png',
'/assets/icons/youtube.png',
'/assets/icons/vimeo.png',
]

